name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    # compile
    - name: compile
      run: gcc ./code/hello.c -o ./hello.out
    # run
    - name: run
      run: ./hello.out
    # remove compiled file
    - name: remove
      run: rm ./hello.out
