name: C/C++ CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    # read file
    - name: read
      env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
          chmod +x ./scripts/compile.sh
          ./scripts/compile.sh
    - name: read env
      run: echo ${{ env }}
    # # set env arr
    # # compile
    # - name: compile
    #   run: gcc ./code/${{ env.arr }}.c -o ./${{ env.arr }}.out
    # # run
    # - name: run
    #   run: ./${{ env.arr }}.out
