name: C/C++ CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    # Compile
    - name: Compile
      run: |
          chmod +x ./scripts/compile.sh
          ./scripts/compile.sh
    - name: read env
      run: echo ${{ env }}